### PR TITLE
Added Powercord support

### PR DESCRIPTION
**Pull request by Frolleks**
I've added Powercord support to make this theme usable for more users. I'm not sure if this will work, because the theme file isn't in the root directory of this repo, but hopefully it works.

### CODE REVIEW

**Comment by Kaiidoo** [comment]
Helloo !

To be honest I think to do a Powercord support and a Vizuality support since a while now but Powercord works with “scss” if I'm not wrong and if I only import the “themes.css” file in the manifest, there will probably be plenty of bugs because this theme change many things in Discord and I haven't looked into how Powercord works more than that yet. It's why I will try to finish the BetterDiscord theme first ( I mean: make the plugin, add the customization guide and change some things in the themes file to works perfectly with the plugin ) and then I will see for others providers.

So, sorry for Powercord and Vizuality users but you will probably have to wait a little longer ...

However I will take the time to see if what you did works perfectly or not, if not I will wait like I wanted to do it but if it works I will probably add it to the theme repository. I don't promise anything but I'll see.

In any case, thank you for your work and don't be worry I will try as soon as possible to do a Powercord support and a Vizuality support, have a good day!

**Comment by rolledev** [comment]
Okay!

**Comment by rolledev** [comment]
and putting the theme.css file in the manifest will not have bugs, I have made themes with just css before and it works very well with powercord.

**Comment by rolledev** [comment]
but thanks for the information!

**Comment by rolledev** [comment]
hmm, i have ran into some bugs when using the theme in powercord. i will try to fix things, and open another pr to this repo if im done fixing things.

**Comment by rolledev** [comment]
once again, thanks for the information

**Comment by Kaiidoo** [comment]
Ok no problem and you're welcome, I'm there for that.

**Pull request closed without merging**
